# Generated by Django 5.2 on 2025-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                ("sender_id", models.CharField(max_length=50, verbose_name="发送者ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("user", "用户消息"), ("system", "系统消息")],
                        default="user",
                        max_length=10,
                        verbose_name="消息类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "ordering": ["created_at"],
            },
        ),
    ]
