# Generated by Django 5.2 on 2025-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(max_length=50, unique=True, verbose_name="消息ID"),
                ),
                ("sender_id", models.CharField(max_length=50, verbose_name="发送者ID")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("user", "用户消息"), ("system", "系统消息")],
                        default="user",
                        max_length=10,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["created_at"], name="myapp_chatm_created_3e9dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender_id"], name="myapp_chatm_sender__09d1f6_idx"
            ),
        ),
    ]
