# Generated by Django 5.2 on 2025-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="dark_mode",
            field=models.BooleanField(default=True),
        ),
    ]
